"""CLI helpers for sanikey."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Never, cast

from . import __version__
from .build import PatientBuildResult, build_all, build_patient
from .config import default_accounts_path, load_accounts
from .containers import stage_container_documents
from .database import build_database
from .dicom import catalog_dicom_studies
from .documents import (
    ExtractedText,
    _known_suffix,
    document_page_count,
    extract_text,
    scan_documents,
)
from .errors import SaniKeyError
from .exports import generate_exports
from .frontend import build_frontend
from .inspection import inspect_patient_documents
from .integrity import check_source_snapshots, write_source_snapshot
from .leaflets import (
    AifaCandidate,
    lookup_aifa_candidate_search,
    medication_fingerprint,
    probe_leaflet_documents,
    write_confirmed_references,
)
from .metadata import load_curated_metadata
from .models import MedicationLeaflet, MedicationLeafletExclusion
from .observation_imports import import_observations
from .privacy import validate_privacy
from .progress import ProgressDots
from .proposals import generate_manual_proposals, review_proposal
from .usb import export_usb, validate_usb

if TYPE_CHECKING:
    from .config import AccountsConfig, PersonConfig
    from .containers import ContainerStagingResult
    from .dicom import DicomStudy
    from .leaflet_tui import LeafletReviewDecision
    from .models import DocumentRecord, Medication, TherapyEpisode


class ItalianArgumentParser(argparse.ArgumentParser):
    """Argument parser with Italian diagnostic text.

    Parameters
    ----------
    *args : object
        Positional arguments forwarded to ``argparse.ArgumentParser``.
    **kwargs : object
        Keyword arguments forwarded to ``argparse.ArgumentParser``.
    """

    def error(self, message: str) -> Never:
        """Print a localized parser error and exit.

        Parameters
        ----------
        message : str
            Error message generated by ``argparse``.

        Returns
        -------
        Never

        Raises
        ------
        SystemExit
            Always raised with exit status ``2``.
        """

        self.print_usage()
        self.exit(2, f"{self.prog}: errore: {_translate_argparse_error(message)}\n")


def _translate_argparse_error(message: str) -> str:
    """Translate common ``argparse`` diagnostics to Italian.

    Parameters
    ----------
    message : str
        Diagnostic message generated by ``argparse``.

    Returns
    -------
    str
        Localized diagnostic message.
    """

    replacements = (
        ("unrecognized arguments:", "argomenti non riconosciuti:"),
        ("the following arguments are required:", "argomenti obbligatori mancanti:"),
        ("invalid choice:", "scelta non valida:"),
        ("expected one argument", "atteso un argomento"),
        ("expected at least one argument", "atteso almeno un argomento"),
    )
    translated = message
    for source, target in replacements:
        translated = translated.replace(source, target)
    return translated


def build_parser() -> argparse.ArgumentParser:
    """Build the top-level CLI parser.

    Parameters
    ----------
    None

    Returns
    -------
    argparse.ArgumentParser
        Configured parser for the SaniKey command line.
    """

    parser = ItalianArgumentParser(
        prog="sanikey",
        description="Documenti medici su chiavetta USB",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    subparsers = parser.add_subparsers(
        dest="command",
        parser_class=ItalianArgumentParser,
    )

    info_parser = subparsers.add_parser(
        "info",
        help="Mostra informazioni progetto",
        description="Mostra le informazioni essenziali del progetto SaniKey.",
    )
    info_parser.set_defaults(func=run_info)

    validate_parser = subparsers.add_parser(
        "validate-config",
        help="Valida la configurazione account locale e i vincoli di privacy",
        description="Verifica configurazione locale, metadati e vincoli di privacy.",
    )
    _add_config_arguments(validate_parser)
    validate_parser.set_defaults(func=run_validate_config)

    list_parser = subparsers.add_parser(
        "list-patients",
        help="Elenca i pazienti configurati",
        description="Elenca i pazienti configurati e il loro stato di abilitazione.",
    )
    _add_config_arguments(list_parser)
    list_parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Include i pazienti disabilitati",
    )
    list_parser.set_defaults(func=run_list_patients)

    scan_parser = subparsers.add_parser(
        "scan-documents",
        help="Scansiona i documenti sorgente configurati",
        description="Inventaria i documenti sorgente e i contenitori rilevati.",
    )
    _add_config_arguments(scan_parser)
    scan_parser.add_argument("-p", "--patient", help="Scansiona solo un id paziente")
    scan_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Stampa una lista leggibile dei documenti acquisiti",
    )
    scan_parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Scrive la lista dei documenti acquisiti in un file",
    )
    scan_parser.add_argument(
        "-f",
        "--format",
        choices=("text", "csv"),
        default=None,
        help="Formato del file di output, valido solo con --output",
    )
    scan_parser.add_argument(
        "-P",
        "--preflight",
        action="store_true",
        help="Esegue controlli pre-build leggeri su archivi e documenti office",
    )
    scan_parser.add_argument(
        "-S",
        "--no-stage-containers",
        action="store_true",
        help="Salta lo staging dei contenitori durante la scansione",
    )
    _add_progress_argument(scan_parser)
    scan_parser.set_defaults(func=run_scan_documents)

    integrity_parser = subparsers.add_parser(
        "document-integrity",
        help="Crea o verifica snapshot di integrita' dei documenti sorgente",
        description="Crea o verifica snapshot di integrita' dei documenti sorgente.",
    )
    _add_config_arguments(integrity_parser, allow_config_flag=True)
    integrity_parser.add_argument(
        "action",
        choices=("before", "after", "check"),
        help="Fase snapshot o azione di verifica",
    )
    integrity_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    integrity_parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        default=Path("local-data"),
        help="Directory per i file snapshot dei pazienti",
    )
    integrity_parser.set_defaults(func=run_document_integrity)

    extract_parser = subparsers.add_parser(
        "extract-text",
        help="Estrae il testo supportato dai documenti sorgente configurati",
        description="Estrae e segnala il testo dei documenti sorgente supportati.",
    )
    _add_config_arguments(extract_parser)
    extract_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    extract_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Include il prefisso SHA-256 del documento nell'output",
    )
    extract_parser.set_defaults(func=run_extract_text)

    observations_parser = subparsers.add_parser(
        "import-observations",
        help="Importa misurazioni longitudinali da CSV e fogli di calcolo",
        description="Importa misurazioni longitudinali da sorgenti dichiarate.",
    )
    _add_config_arguments(observations_parser, allow_config_flag=True)
    observations_parser.add_argument(
        "patient",
        nargs="?",
        help="Importa solo un id paziente",
    )
    observations_parser.set_defaults(func=run_import_observations)

    dicom_parser = subparsers.add_parser(
        "process-dicom",
        help="Cataloga supporti DICOM e directory di espansione manuale",
        description="Cataloga studi DICOM e verifica i supporti che li contengono.",
    )
    _add_config_arguments(dicom_parser)
    dicom_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    dicom_parser.add_argument(
        "-S",
        "--no-stage-containers",
        action="store_true",
        help="Salta lo staging dei contenitori durante il catalogo DICOM",
    )
    dicom_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Stampa anche la tabella tecnica degli studi DICOM",
    )
    _add_progress_argument(dicom_parser)
    dicom_parser.set_defaults(func=run_process_dicom)

    database_parser = subparsers.add_parser(
        "build-database",
        help="Costruisce database SQLite di archivio per paziente",
        description="Costruisce il database SQLite per i pazienti selezionati.",
    )
    _add_config_arguments(database_parser)
    database_parser.add_argument(
        "-p", "--patient", help="Costruisce solo un id paziente"
    )
    database_parser.set_defaults(func=run_build_database)

    build_patient_parser = subparsers.add_parser(
        "build-patient",
        help="Esegue la pipeline di build locale per un paziente",
        description="Esegue l'intera build locale per un solo paziente.",
    )
    _add_config_arguments(build_patient_parser, allow_config_flag=True)
    build_patient_parser.add_argument("patient")
    build_patient_parser.add_argument(
        "-m",
        "--mode",
        choices=("full", "incremental", "validation"),
        default="incremental",
    )
    _add_progress_argument(build_patient_parser)
    build_patient_parser.set_defaults(func=run_build_patient)

    build_all_parser = subparsers.add_parser(
        "build-all",
        help="Esegue la pipeline di build locale per tutti i pazienti abilitati",
        description="Esegue l'intera build locale per tutti i pazienti abilitati.",
    )
    _add_config_arguments(build_all_parser)
    build_all_parser.add_argument(
        "-m",
        "--mode",
        choices=("full", "incremental", "validation"),
        default="incremental",
    )
    _add_progress_argument(build_all_parser)
    build_all_parser.set_defaults(func=run_build_all)

    update_parser = subparsers.add_parser(
        "update-archive",
        help="Esegue l'aggiornamento incrementale predefinito dell'archivio",
        description="Aggiorna incrementalmente l'archivio di uno o tutti i pazienti.",
    )
    _add_config_arguments(update_parser)
    update_parser.add_argument("-p", "--patient", help="Aggiorna solo un id paziente")
    update_parser.set_defaults(func=run_update_archive)

    proposals_parser = subparsers.add_parser(
        "generate-proposals",
        help="Sperimentale: genera un segnaposto per revisione manuale",
        description="Sperimentale: genera un segnaposto non operativo per revisione.",
    )
    _add_config_arguments(proposals_parser)
    proposals_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    proposals_parser.set_defaults(func=run_generate_proposals)

    review_parser = subparsers.add_parser(
        "review-proposal",
        help="Sperimentale: cambia lo stato di una proposta salvata",
        description="Sperimentale: cambia lo stato senza promuovere metadati curati.",
    )
    _add_config_arguments(review_parser, allow_config_flag=True)
    review_parser.add_argument("patient")
    review_parser.add_argument("proposal_id")
    review_parser.add_argument("status", choices=("approved", "rejected"))
    review_parser.set_defaults(func=run_review_proposal)

    leaflet_parser = subparsers.add_parser(
        "resolve-medication-leaflets",
        help="Cerca e conferma riferimenti AIFA per FI e RCP",
        description=(
            "Verifica i riferimenti AIFA e richiede una scelta solo nei casi ambigui."
        ),
    )
    _add_config_arguments(leaflet_parser, allow_config_flag=True)
    leaflet_parser.add_argument("patient", help="Id del paziente da elaborare")
    leaflet_parser.add_argument(
        "-s",
        "--select",
        action="append",
        default=[],
        metavar="FARMACO=NUMERO",
        help="Conferma un candidato numerato, per esempio metformina=1",
    )
    leaflet_parser.add_argument(
        "-q",
        "--query",
        action="append",
        default=[],
        metavar="FARMACO=TESTO",
        help="Cerca manualmente AIFA per un farmaco, per esempio metformina=Glucophage",
    )
    leaflet_parser.add_argument(
        "-n",
        "--mark-non-aifa",
        action="append",
        default=[],
        metavar="FARMACO",
        help="Segna un farmaco senza foglio illustrativo AIFA applicabile",
    )
    leaflet_parser.set_defaults(func=run_resolve_medication_leaflets)

    exports_parser = subparsers.add_parser(
        "generate-exports",
        help="Genera export JSON statici per frontend, ricerca e timeline",
        description="Genera gli export JSON statici per consultazione e ricerca.",
    )
    _add_config_arguments(exports_parser)
    exports_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    exports_parser.set_defaults(func=run_generate_exports)

    web_parser = subparsers.add_parser(
        "build-web",
        help="Genera file frontend statici",
        description="Genera il frontend statico del paziente selezionato.",
    )
    _add_config_arguments(web_parser)
    web_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    web_parser.set_defaults(func=run_build_web)

    export_parser = subparsers.add_parser(
        "export-usb",
        help="Esporta gli artefatti generati in una directory layout USB",
        description="Copia gli artefatti generati in una directory USB pronta all'uso.",
    )
    _add_config_arguments(export_parser, allow_config_flag=True)
    export_parser.add_argument("target", type=Path)
    _add_progress_argument(export_parser)
    export_parser.set_defaults(func=run_export_usb)

    validate_usb_parser = subparsers.add_parser(
        "validate-usb",
        help="Valida una directory layout USB generata",
        description="Verifica integrita' e struttura di una directory USB generata.",
    )
    validate_usb_parser.add_argument("target", type=Path)
    validate_usb_parser.set_defaults(func=run_validate_usb)

    deploy_parser = subparsers.add_parser(
        "deploy-usb",
        help="Costruisce tutti i pazienti abilitati e li esporta in un layout USB",
        description="Costruisce ed esporta tutti i pazienti abilitati su USB.",
    )
    _add_config_arguments(deploy_parser, allow_config_flag=True)
    deploy_parser.add_argument("target", type=Path)
    _add_progress_argument(deploy_parser)
    deploy_parser.set_defaults(func=run_deploy_usb)
    return parser


def run_info(_args: argparse.Namespace) -> int:
    """Print a minimal project information summary.

    Parameters
    ----------
    _args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    print("progetto=sanikey")
    print("package=sanikey")
    print("cli=sanikey")
    print(f"versione={__version__}")
    return 0


def run_validate_config(args: argparse.Namespace) -> int:
    """Validate accounts configuration and privacy constraints.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        validate_privacy(config, repo_root=args.repo_root)
        for person in config.enabled_people():
            load_curated_metadata(person.metadata_directory)
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    enabled = len(config.enabled_people())
    total = len(config.people)
    print(f"configurazione={_repo_relative_path(config.path)}")
    print(f"pazienti={total}")
    print(f"abilitati={enabled}")
    print("stato=ok")
    return 0


def run_list_patients(args: argparse.Namespace) -> int:
    """List configured patient identifiers.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    selected = sorted(
        config.people if args.all else config.enabled_people(),
        key=lambda person: (
            not person.enabled,
            person.id.casefold(),
        ),
    )
    id_width = max((len(person.id) for person in selected), default=0)
    state_width = len("disabilitato") if args.all else len("abilitato")
    for person in selected:
        state = "abilitato" if person.enabled else "disabilitato"
        print(
            f"{person.id:<{id_width}}   {state:<{state_width}}   {person.display_name}"
        )
    return 0


def run_scan_documents(args: argparse.Namespace) -> int:
    """Scan configured source documents and optionally print inventory rows.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    if args.output is None and args.format is not None:
        print("ERRORE: --format e' valido solo con --output")
        return 1
    try:
        config = load_accounts(_config_path(args))
        selected_people = _selected_people(config, args.patient)
        for person in selected_people:
            load_curated_metadata(person.metadata_directory)
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    output_rows: list[tuple[PersonConfig, DocumentRecord]] = []
    progress = _progress_from_args(args)
    for person in selected_people:
        inspection = inspect_patient_documents(
            person,
            preflight=args.preflight,
            stage_containers=not args.no_stage_containers,
            progress=progress,
        )
        warning_messages = (
            *inspection.warning_messages,
            *inspection.preflight_warning_messages,
        )
        summary = (
            f"paziente={person.id} files={len(inspection.inventory)} "
            f"documenti={len(inspection.documents)} "
            f"duplicati={len(inspection.duplicates)} avvisi={len(warning_messages)} "
            f"esclusi={len(inspection.excluded_files)}"
        )
        if inspection.container_staging is not None:
            staged_container_ids = {
                member.container_id for member in inspection.container_staging.members
            }
            summary = (
                f"{summary} archivi_preparati={len(staged_container_ids)} "
                f"membri_in_archivi={len(inspection.container_staging.members)} "
                f"documenti_derivati={len(inspection.container_staging.documents)}"
            )
        print(summary)
        for warning in warning_messages:
            print(f"AVVISO: {warning}")
        if args.verbose:
            print(_format_scan_verbose(person, inspection.documents))
        output_rows.extend((person, document) for document in inspection.documents)
    if args.output is not None:
        try:
            _write_scan_output(
                args.output,
                output_rows,
                output_format=args.format or "text",
            )
        except OSError as exc:
            print(
                "ERRORE: impossibile scrivere l'output della scansione "
                f"{_repo_relative_path(args.output)}: {_repo_relative_text(str(exc))}"
            )
            return 1
    return 0


def run_document_integrity(args: argparse.Namespace) -> int:
    """Create or verify source document integrity snapshots.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected_people = _selected_people(config, args.patient)
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    status = 0
    for person in selected_people:
        try:
            if args.action in {"before", "after"}:
                result = write_source_snapshot(
                    person,
                    label=args.action,
                    output_dir=args.output_dir,
                )
            else:
                result = check_source_snapshots(person, output_dir=args.output_dir)
        except OSError as exc:
            print(f"ERRORE: paziente={person.id} {exc}")
            status = 1
            continue
        print(
            f"paziente={result.patient_id} azione={args.action} "
            f"stato={result.status} "
            f"sha256={_repo_relative_path(result.sha256_path)} "
            f"mtime={_repo_relative_path(result.mtime_path)}"
        )
        if result.status != "ok" and args.action == "check":
            status = 1
    return status


def _format_scan_verbose(
    person: PersonConfig,
    documents: tuple[DocumentRecord, ...],
) -> str:
    """Render a readable scan inventory table for stdout.

    Parameters
    ----------
    person : PersonConfig
        Patient configuration.
    documents : tuple[DocumentRecord, ...]
        Deduplicated document records.

    Returns
    -------
    str
        Human-readable table.
    """

    if not documents:
        return f"paziente={person.id} documenti_acquisiti=0"
    rows = [
        (
            "paziente",
            "tipo",
            "data",
            "categoria",
            "sha256",
            "file",
        ),
        *(
            (
                document.patient_id,
                document.kind,
                _format_display_date(document.date),
                document.category,
                document.sha256[:12],
                _source_relative_path(person, document),
            )
            for document in documents
        ),
    ]
    widths = tuple(
        max(len(row[index]) for row in rows) for index in range(len(rows[0]))
    )
    rendered = [f"paziente={person.id} documenti_acquisiti={len(documents)}"]
    for row_index, row in enumerate(rows):
        rendered.append(_format_table_row(row, widths))
        if row_index == 0:
            rendered.append(_format_scan_separator(row, widths))
    return "\n".join(rendered)


def _format_table_row(row: tuple[str, ...], widths: tuple[int, ...]) -> str:
    """Render one table row without padding the final column.

    Parameters
    ----------
    row : tuple[str, ...]
        Table row values.
    widths : tuple[int, ...]
        Column widths.

    Returns
    -------
    str
        Rendered row.
    """

    padded = [value.ljust(widths[index]) for index, value in enumerate(row[:-1])]
    return "  ".join((*padded, row[-1])).rstrip()


def _format_scan_separator(row: tuple[str, ...], widths: tuple[int, ...]) -> str:
    """Render the scan table separator.

    Parameters
    ----------
    row : tuple[str, ...]
        Header row.
    widths : tuple[int, ...]
        Column widths.

    Returns
    -------
    str
        Separator row.
    """

    separator = tuple(
        "-" * (4 if index == len(row) - 1 else min(widths[index], 20))
        for index in range(len(row))
    )
    return _format_table_row(separator, widths)


def _write_scan_output(
    output_path: Path,
    rows: list[tuple[PersonConfig, DocumentRecord]],
    *,
    output_format: str,
) -> None:
    """Write scan inventory rows to a user-selected file.

    Parameters
    ----------
    output_path : pathlib.Path
        Destination file path.
    rows : list[tuple[PersonConfig, DocumentRecord]]
        Patient and document rows.
    output_format : str
        Output format, either ``text`` or ``csv``.

    Returns
    -------
    None
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_format == "csv":
        _write_scan_csv(output_path, rows)
        return
    _write_scan_text(output_path, rows)


def _write_scan_csv(
    output_path: Path,
    rows: list[tuple[PersonConfig, DocumentRecord]],
) -> None:
    """Write scan inventory rows as CSV.

    Parameters
    ----------
    output_path : pathlib.Path
        Destination file path.
    rows : list[tuple[PersonConfig, DocumentRecord]]
        Patient and document rows.

    Returns
    -------
    None
    """

    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            ("paziente", "tipo", "categoria", "data", "titolo", "sha256", "path")
        )
        for _person, document in rows:
            writer.writerow(_scan_legacy_row(document))


def _write_scan_text(
    output_path: Path,
    rows: list[tuple[PersonConfig, DocumentRecord]],
) -> None:
    """Write scan inventory rows in legacy tab-separated text format.

    Parameters
    ----------
    output_path : pathlib.Path
        Destination file path.
    rows : list[tuple[PersonConfig, DocumentRecord]]
        Patient and document rows.

    Returns
    -------
    None
    """

    lines = ["\t".join(_scan_legacy_row(document)) for _person, document in rows]
    output_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def _scan_legacy_row(document: DocumentRecord) -> tuple[str, ...]:
    """Return the legacy scan inventory row.

    Parameters
    ----------
    document : DocumentRecord
        Document record.

    Returns
    -------
    tuple[str, ...]
        Legacy row fields.
    """

    return (
        document.patient_id,
        document.kind,
        document.category,
        document.date or "",
        document.title,
        document.sha256,
        str(document.path),
    )


def _format_display_date(value: str | None) -> str:
    """Format an ISO date for display.

    Parameters
    ----------
    value : str | None
        ISO date or missing value.

    Returns
    -------
    str
        Italian display date or empty string.
    """

    if value is None:
        return ""
    match = value.split("-")
    if len(match) == 3 and all(part.isdigit() for part in match):
        return f"{match[2]}/{match[1]}/{match[0]}"
    return value


def _source_relative_path(person: PersonConfig, document: DocumentRecord) -> str:
    """Return a document path relative to the source root when possible.

    Parameters
    ----------
    person : PersonConfig
        Patient configuration.
    document : DocumentRecord
        Document record.

    Returns
    -------
    str
        Relative path or absolute path fallback.
    """

    try:
        return document.path.relative_to(person.source_documents).as_posix()
    except ValueError:
        return str(document.path)


def _repo_relative_path(path: Path, *, repo_root: Path | None = None) -> str:
    """Return a path relative to the repository root when possible.

    Parameters
    ----------
    path : pathlib.Path
        Path to render.
    repo_root : pathlib.Path | None, optional
        Repository root. When omitted, the current working directory is used.

    Returns
    -------
    str
        Repository-relative path when ``path`` is inside ``repo_root``,
        otherwise the original path string.
    """

    selected_root = Path.cwd() if repo_root is None else repo_root
    try:
        return (
            path.resolve(strict=False)
            .relative_to(selected_root.resolve(strict=False))
            .as_posix()
        )
    except ValueError:
        return str(path)


def _repo_relative_text(value: str, *, repo_root: Path | None = None) -> str:
    """Abbreviate repository paths embedded in a diagnostic message.

    Parameters
    ----------
    value : str
        Diagnostic text that can contain one or more absolute paths.
    repo_root : pathlib.Path | None, optional
        Repository root. When omitted, the current working directory is used.

    Returns
    -------
    str
        Diagnostic text with paths below the repository rendered relatively.
    """

    selected_root = Path.cwd() if repo_root is None else repo_root
    root_text = f"{selected_root.resolve(strict=False)}/"
    return value.replace(root_text, "")


def _format_extract_text_result(
    person: PersonConfig,
    document: DocumentRecord,
    extracted: ExtractedText,
    *,
    repo_root: Path | None = None,
    verbose: bool = False,
) -> str:
    """Format one text extraction result for human-readable CLI output.

    Parameters
    ----------
    person : PersonConfig
        Patient configuration.
    document : DocumentRecord
        Source document.
    extracted : sanikey.documents.ExtractedText
        Extracted text payload.
    repo_root : pathlib.Path | None, optional
        Repository root used to abbreviate paths.
    verbose : bool, optional
        Whether to include the short SHA-256 content fingerprint.

    Returns
    -------
    str
        One aligned output row with patient id, page count, warning count
        and source path. Verbose output also includes the short SHA-256 content
        fingerprint.
    """

    fingerprint = f"sha256={document.sha256[:12]} " if verbose else ""
    pages = document_page_count(document)
    rendered_pages = "?" if pages is None else str(pages)
    return (
        f"{person.id:<12} "
        f"{fingerprint}"
        f"pagine={rendered_pages:>5} "
        f"avvisi={len(extracted.warnings):>3} "
        f"{_repo_relative_path(document.path, repo_root=repo_root)}"
    )


def run_extract_text(args: argparse.Namespace) -> int:
    """Extract text from configured source documents.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    for person in _selected_people(config, args.patient):
        for document in scan_documents(person):
            extracted = extract_text(document)
            print(
                _format_extract_text_result(
                    person,
                    document,
                    extracted,
                    verbose=args.verbose,
                )
            )
            for warning in extracted.warnings:
                path = _repo_relative_path(document.path)
                print(f"AVVISO: {path}: {warning}")
    return 0


def run_process_dicom(args: argparse.Namespace) -> int:
    """Catalog DICOM supports for configured patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    for person in _selected_people(config, args.patient):
        source_documents = scan_documents(person)
        documents = source_documents
        progress = _progress_from_args(args) if args.verbose else None
        staging = None
        if not args.no_stage_containers:
            staging = stage_container_documents(
                person,
                source_documents,
                progress=progress,
                progress_label=f"stage-containers {person.id}",
            )
            documents = (*source_documents, *staging.documents)
        studies = catalog_dicom_studies(
            person,
            documents,
            progress=progress,
            progress_label=f"catalog-dicom {person.id}",
        )
        if args.verbose:
            _print_process_dicom_verbose(person.id, studies, staging)
        else:
            _print_process_dicom_human(person.id, source_documents, studies, staging)
    return 0


_DICOM_SUPPORT_KINDS = frozenset(
    {
        "dicom_7z",
        "dicom_img",
        "dicom_iso",
        "dicom_rar",
        "dicom_tar_xz",
        "dicom_zip",
    }
)


def _print_process_dicom_human(
    patient_id: str,
    source_documents: tuple[DocumentRecord, ...],
    studies: tuple[DicomStudy, ...],
    staging: ContainerStagingResult | None,
) -> None:
    """Print the human DICOM catalog summary.

    Parameters
    ----------
    patient_id : str
        Patient identifier.
    source_documents : tuple[sanikey.models.DocumentRecord, ...]
        Source document records.
    studies : tuple[sanikey.dicom.DicomStudy, ...]
        Cataloged DICOM study/support records.
    staging : sanikey.containers.ContainerStagingResult | None
        Optional container staging result.

    Returns
    -------
    None
    """

    containers = tuple(
        document
        for document in source_documents
        if _known_suffix(document.path)
        in {".7z", ".img", ".iso", ".rar", ".tar.xz", ".zip"}
    )
    support_rows = {
        study.support_path: study
        for study in studies
        if study.support_kind in _DICOM_SUPPORT_KINDS
    }
    study_counts = _dicom_study_counts_by_container(containers, studies, staging)
    matched_staging_warnings: set[int] = set()
    for container in containers:
        study = support_rows.get(container.path)
        staging_warnings = _matching_staging_warnings(container.path, staging)
        matched_staging_warnings.update(staging_warnings)
        warnings = (
            *(study.warnings if study is not None else ()),
            *(
                staging.warning_messages[index]
                for index in staging_warnings
                if staging is not None
            ),
        )
        result = _format_process_dicom_human_result(
            study_counts.get(container.document_id, 0),
            warnings,
        )
        support_kind = study.support_kind if study is not None else container.kind
        print(
            "\t".join(
                (
                    patient_id,
                    support_kind,
                    result,
                    _repo_relative_path(container.path),
                )
            )
        )
    if staging is not None:
        for index, warning in enumerate(staging.warning_messages):
            if index in matched_staging_warnings:
                continue
            print(
                "\t".join(
                    (
                        patient_id,
                        "staging",
                        f"problema: {_single_line_text(_repo_relative_text(warning))}",
                    )
                )
            )


_DICOM_STUDY_KINDS = frozenset({"dicom_study", "dicomdir_study", "dicom_file"})


def _format_process_dicom_human_result(
    study_count: int,
    warnings: tuple[str, ...],
) -> str:
    """Format the human result for one DICOM archive/support.

    Parameters
    ----------
    study_count : int
        Number of actual DICOM studies found below the support.
    warnings : tuple[str, ...]
        Non-fatal warnings associated with the support.

    Returns
    -------
    str
        Human result field.
    """

    if warnings:
        return "problema: " + "; ".join(
            _single_line_text(_repo_relative_text(item)) for item in warnings
        )
    if study_count == 0:
        return "nessuno studio DICOM"
    if study_count == 1:
        return "ok"
    return f"piu studi DICOM: {study_count}"


def _dicom_study_counts_by_container(
    containers: tuple[DocumentRecord, ...],
    studies: tuple[DicomStudy, ...],
    staging: ContainerStagingResult | None,
) -> dict[str, int]:
    """Count actual DICOM studies attributable to each source container.

    Parameters
    ----------
    containers : tuple[sanikey.models.DocumentRecord, ...]
        Source containers to summarize.
    studies : tuple[sanikey.dicom.DicomStudy, ...]
        Cataloged DICOM records.
    staging : sanikey.containers.ContainerStagingResult | None
        Optional staging result.

    Returns
    -------
    dict[str, int]
        Mapping from source container document id to number of actual studies.
    """

    if staging is None:
        return {
            container.document_id: sum(
                1
                for study in studies
                if study.support_path == container.path
                and study.support_kind in _DICOM_STUDY_KINDS
            )
            for container in containers
        }
    descendants = {
        container.document_id: _descendant_container_ids(container.document_id, staging)
        for container in containers
    }
    counts = dict.fromkeys((container.document_id for container in containers), 0)
    for study in studies:
        if study.support_kind not in _DICOM_STUDY_KINDS:
            continue
        owners = {
            owner_id
            for path in (study.support_paths or (study.support_path,))
            if (owner_id := _staged_document_container_id(path, staging)) is not None
        }
        for container_id, descendant_ids in descendants.items():
            if owners & descendant_ids:
                counts[container_id] += 1
    return counts


def _descendant_container_ids(
    container_id: str,
    staging: ContainerStagingResult,
) -> set[str]:
    """Return a source container and all nested container ids.

    Parameters
    ----------
    container_id : str
        Root container document id.
    staging : sanikey.containers.ContainerStagingResult
        Container staging result.

    Returns
    -------
    set[str]
        Root and descendant container ids.
    """

    children: dict[str, set[str]] = {}
    for member in staging.members:
        if getattr(member, "kind", None) not in {"archive", "dicom_img", "dicom_iso"}:
            continue
        children.setdefault(member.container_id, set()).add(member.document_id)
    pending = [container_id]
    seen: set[str] = set()
    while pending:
        current = pending.pop()
        if current in seen:
            continue
        seen.add(current)
        pending.extend(sorted(children.get(current, ())))
    return seen


def _staged_document_container_id(
    path: Path,
    staging: ContainerStagingResult,
) -> str | None:
    """Return the immediate container id for a staged document path.

    Parameters
    ----------
    path : pathlib.Path
        Staged file path.
    staging : sanikey.containers.ContainerStagingResult
        Container staging result.

    Returns
    -------
    str | None
        Immediate container id when ``path`` belongs to a staged member.
    """

    path_text = str(path)
    for member in staging.members:
        if member.path == path_text:
            return member.container_id
    for document in staging.documents:
        if document.container_id is None:
            continue
        try:
            path.relative_to(document.path.parent)
        except ValueError:
            continue
        return document.container_id
    return None


def _single_line_text(value: str) -> str:
    """Collapse diagnostic text to one printable line.

    Parameters
    ----------
    value : str
        Diagnostic text.

    Returns
    -------
    str
        Text with internal whitespace collapsed.
    """

    return " ".join(value.split())


def _matching_staging_warnings(
    path: Path,
    staging: ContainerStagingResult | None,
) -> tuple[int, ...]:
    """Return staging warning indexes that refer to a DICOM support.

    Parameters
    ----------
    path : pathlib.Path
        DICOM support or container path.
    staging : sanikey.containers.ContainerStagingResult | None
        Optional staging result.

    Returns
    -------
    tuple[int, ...]
        Indexes of staging warnings mentioning the support path.
    """

    if staging is None:
        return ()
    support_path = str(path)
    return tuple(
        index
        for index, warning in enumerate(staging.warning_messages)
        if support_path in warning
    )


def _print_process_dicom_verbose(
    patient_id: str,
    studies: tuple[DicomStudy, ...],
    staging: ContainerStagingResult | None,
) -> None:
    """Print the verbose technical DICOM catalog.

    Parameters
    ----------
    patient_id : str
        Patient identifier.
    studies : tuple[object, ...]
        Cataloged DICOM study/support records.
    staging : object | None
        Optional container staging result.

    Returns
    -------
    None
    """

    summary = f"paziente={patient_id} studi_dicom={len(studies)}"
    if staging is not None:
        staged_container_ids = {member.container_id for member in staging.members}
        summary = (
            f"{summary} archivi_preparati={len(staged_container_ids)} "
            f"membri_in_archivi={len(staging.members)} "
            f"documenti_derivati={len(staging.documents)}"
        )
    print(summary)
    for study in studies:
        extracted_path = study.extracted_path
        extracted = (
            "" if extracted_path is None else _repo_relative_path(extracted_path)
        )
        print(
            "\t".join(
                (
                    study.patient_id,
                    study.support_kind,
                    str(study.instance_count),
                    str(len(study.viewer_paths)),
                    str(len(study.warnings)),
                    study.study_date or "",
                    study.study_instance_uid or "",
                    study.study_description or "",
                    _repo_relative_path(study.support_path),
                    extracted,
                )
            )
        )
        for warning in study.warnings:
            path = _repo_relative_path(study.support_path)
            print(f"AVVISO: {path}: {warning}")
    if staging is not None:
        for warning in staging.warning_messages:
            print(f"AVVISO: {_repo_relative_text(warning)}")


def run_build_database(args: argparse.Namespace) -> int:
    """Build SQLite databases for configured patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    for person in _selected_people(config, args.patient):
        documents = scan_documents(person)
        metadata = load_curated_metadata(person.metadata_directory)
        dicom_studies = catalog_dicom_studies(person, documents)
        result = build_database(person, documents, metadata, dicom_studies)
        print(
            f"paziente={person.id} database={_repo_relative_path(result.path)} "
            f"documenti={result.documents} studi_dicom={result.dicom_studies}"
        )
    return 0


def run_build_patient(args: argparse.Namespace) -> int:
    """Run the local build pipeline for one patient.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected = _selected_people(config, args.patient)
        if not selected:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        _print_build_result(
            build_patient(
                selected[0],
                mode=args.mode,
                progress=_progress_from_args(args),
            )
        )
    except (SaniKeyError, ValueError) as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_import_observations(args: argparse.Namespace) -> int:
    """Run observation import for configured patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected = _selected_people(config, args.patient)
        if args.patient and not selected:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        for person in selected:
            result = import_observations(person)
            print(
                f"paziente={result.patient_id} serie={result.series} "
                f"punti={result.points}"
            )
            for warning in result.warnings:
                print(f"AVVISO: {warning}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_build_all(args: argparse.Namespace) -> int:
    """Run the local build pipeline for all enabled patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for result in build_all(
            config,
            mode=args.mode,
            progress=_progress_from_args(args),
        ):
            _print_build_result(result)
    except (SaniKeyError, ValueError) as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def _progress_from_args(args: argparse.Namespace) -> ProgressDots:
    """Build a progress reporter from parsed CLI arguments.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    ProgressDots
        Progress reporter configured for the current terminal.
    """

    return ProgressDots(enabled=not getattr(args, "no_progress", False))


def run_update_archive(args: argparse.Namespace) -> int:
    """Run the default incremental archive update.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    if args.patient is None:
        args.mode = "incremental"
        return run_build_all(args)
    args.mode = "incremental"
    args.patient = str(args.patient)
    return run_build_patient(args)


def run_generate_proposals(args: argparse.Namespace) -> int:
    """Generate deterministic manual-review proposals.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for person in _selected_people(config, args.patient):
            proposals = generate_manual_proposals(person.metadata_directory)
            print(f"paziente={person.id} proposte={len(proposals)}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_review_proposal(args: argparse.Namespace) -> int:
    """Approve or reject one stored proposal.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected = _selected_people(config, args.patient)
        if not selected:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        updated = review_proposal(
            selected[0].metadata_directory,
            args.proposal_id,
            args.status,
        )
        print(f"proposta={updated.id} stato={updated.status}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_resolve_medication_leaflets(  # noqa: C901, PLR0912
    args: argparse.Namespace,
) -> int:
    """Find and persist explicitly confirmed AIFA medication references.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        people = _selected_people(config, args.patient)
        if len(people) != 1:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        selected = _parse_leaflet_selections(args.select)
        queries = _parse_leaflet_queries(getattr(args, "query", []))
        marked_non_aifa = set(getattr(args, "mark_non_aifa", []))
        metadata = load_curated_metadata(people[0].metadata_directory)
        _validate_leaflet_option_ids(
            {medication.id for medication in metadata.medications},
            selected,
            queries,
            marked_non_aifa,
        )
        references = {
            reference.medication_id: reference
            for reference in metadata.medication_leaflets
        }
        exclusions = {
            exclusion.medication_id: exclusion
            for exclusion in metadata.medication_leaflet_exclusions
        }
        unresolved = 0
        for medication in metadata.medications:
            requires_reconfirmation = False
            if medication.id in marked_non_aifa:
                references.pop(medication.id, None)
                exclusions[medication.id] = MedicationLeafletExclusion(medication.id)
                print(f"farmaco={medication.id} stato=non_aifa confermato")
                continue
            if medication.id in exclusions:
                print(f"farmaco={medication.id} stato=non_aifa conservato")
                continue
            search = lookup_aifa_candidate_search(
                medication, query=queries.get(medication.id)
            )
            current = references.get(medication.id)
            if search is None:
                if current is not None:
                    print(
                        f"farmaco={medication.id} riferimento AIFA conservato "
                        "(verifica AIFA non disponibile)"
                    )
                else:
                    print(
                        f"farmaco={medication.id} ricerca AIFA non disponibile; "
                        "nessun riferimento creato"
                    )
                    unresolved += 1
                continue
            candidates = search.exact or search.review
            current_index = next(
                (
                    index
                    for index, candidate in enumerate(search.all_candidates, start=1)
                    if current is not None
                    and candidate.codice_sis == current.codice_sis
                    and candidate.aic6 == current.aic6
                ),
                None,
            )
            if (
                current is not None
                and current_index is not None
                and medication.id not in queries
            ):
                failures = probe_leaflet_documents(current)
                if failures:
                    if not any(
                        failure.reason.startswith("HTTP 404") for failure in failures
                    ):
                        print(
                            f"farmaco={medication.id} riferimento AIFA conservato "
                            "(verifica FI/RCP non disponibile)"
                        )
                        continue
                    references.pop(medication.id, None)
                    requires_reconfirmation = True
                    print(
                        f"farmaco={medication.id} riferimento AIFA senza FI/RCP: "
                        + "; ".join(
                            f"{failure.kind} {failure.reason}" for failure in failures
                        )
                    )
                    current = None
                else:
                    references[medication.id] = MedicationLeaflet(
                        medication.id,
                        current.codice_sis,
                        current.aic6,
                        current.downloaded_at,
                        medication_fingerprint(medication),
                    )
                    print(f"farmaco={medication.id} riferimento AIFA verificato")
                    continue
            if current is not None and medication.id in queries:
                references.pop(medication.id, None)
                current = None
            choice = selected.get(medication.id)
            if (
                choice is None
                and len(search.exact) == 1
                and not requires_reconfirmation
            ):
                choice = 1
                print(
                    f"farmaco={medication.id} riferimento AIFA confermato automaticamente"
                )
            while choice is None:
                therapies = tuple(
                    therapy
                    for therapy in metadata.therapies
                    if therapy.medication_id == medication.id
                )
                decision = _leaflet_menu_choice(medication, therapies, candidates)
                if decision is not None:
                    if decision.exit_requested:
                        print(
                            "operazione interrotta dall'operatore; nessuna modifica salvata"
                        )
                        return 0
                    if getattr(decision, "mark_non_aifa", False):
                        references.pop(medication.id, None)
                        exclusions[medication.id] = MedicationLeafletExclusion(
                            medication.id
                        )
                        print(f"farmaco={medication.id} stato=non_aifa confermato")
                        break
                    manual_query = getattr(decision, "manual_query", None)
                    if manual_query:
                        search = lookup_aifa_candidate_search(
                            medication, query=manual_query
                        )
                        if search is None:
                            print(
                                f"farmaco={medication.id} ricerca AIFA non disponibile; "
                                "nessun riferimento creato"
                            )
                            unresolved += 1
                            break
                        candidates = search.all_candidates
                        continue
                    choice = decision.candidate_index
                break
            if medication.id in exclusions:
                continue
            if choice is None:
                _print_leaflet_candidates(medication.id, medication.name, candidates)
                unresolved += 1
                continue
            if choice < 1 or choice > len(candidates):
                print(f"ERRORE: selezione non valida per {medication.id}: {choice}")
                return 1
            candidate = candidates[choice - 1]
            reference = MedicationLeaflet(
                medication.id,
                candidate.codice_sis,
                candidate.aic6,
                source_fingerprint=medication_fingerprint(medication),
            )
            failures = probe_leaflet_documents(reference)
            if failures:
                print(
                    f"farmaco={medication.id} candidato AIFA senza FI/RCP: "
                    + "; ".join(
                        f"{failure.kind} {failure.reason}" for failure in failures
                    )
                )
                unresolved += 1
                continue
            references[medication.id] = reference
        if references or exclusions:
            target = write_confirmed_references(
                people[0].metadata_directory,
                tuple(references.values()),
                tuple(exclusions.values()),
            )
            print(
                f"paziente={people[0].id} riferimenti_confermati={len(references)} "
                f"non_aifa={len(exclusions)} da_confermare={unresolved} "
                f"{_repo_relative_path(target)}"
            )
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def _leaflet_menu_choice(
    medication: Medication,
    therapies: tuple[TherapyEpisode, ...],
    candidates: tuple[AifaCandidate, ...],
) -> LeafletReviewDecision | None:
    """Open the ncurses review screen on an interactive terminal.

    Parameters
    ----------
    medication : sanikey.models.Medication
        Curated medication identity displayed in the right pane.
    therapies : tuple[sanikey.models.TherapyEpisode, ...]
        Curated therapy episodes linked to the medication.
    candidates : tuple[sanikey.leaflets.AifaCandidate, ...]
        AIFA candidates in their stable display order.

    Returns
    -------
    sanikey.leaflet_tui.LeafletReviewDecision | None
        Review decision, or ``None`` when no interactive terminal is available.
    """

    if not (sys.stdin.isatty() and sys.stdout.isatty()):
        return None
    from .leaflet_tui import choose_aifa_candidate

    return choose_aifa_candidate(medication, therapies, candidates)


def _print_leaflet_candidates(
    medication_id: str,
    medication_name: str,
    candidates: tuple[AifaCandidate, ...],
) -> None:
    """Print an ambiguity report suitable for a non-interactive terminal.

    Parameters
    ----------
    medication_id : str
        Curated medication identifier.
    medication_name : str
        Curated medication name.
    candidates : tuple[sanikey.leaflets.AifaCandidate, ...]
        AIFA candidates in their stable display order.

    Returns
    -------
    None
    """

    print(f"farmaco={medication_id} nome={medication_name} candidati={len(candidates)}")
    for index, candidate in enumerate(candidates, start=1):
        mismatch = (
            f" da verificare: {', '.join(candidate.mismatches)}"
            if candidate.mismatches
            else ""
        )
        print(
            f"  {index}. {candidate.title} AIFA={candidate.codice_sis}/{candidate.aic6}"
            f"{mismatch}"
        )
    if candidates:
        print("  usare --select FARMACO=NUMERO per confermare")
    print("  usare --query FARMACO=TESTO per una ricerca manuale")
    print("  usare --mark-non-aifa FARMACO se il farmaco non ha un FI AIFA applicabile")


def _parse_leaflet_selections(values: list[str]) -> dict[str, int]:
    """Parse ``medication_id=number`` confirmation arguments.

    Parameters
    ----------
    values : list[str]
        Raw command-line selections.

    Returns
    -------
    dict[str, int]
        Candidate index keyed by medication id.

    Raises
    ------
    SaniKeyError
        If a selection is malformed.
    """

    selected = {}
    for value in values:
        medication_id, separator, number = value.partition("=")
        if not medication_id or separator != "=" or not number.isdigit():
            message = f"selezione foglio illustrativo non valida: {value}"
            raise SaniKeyError(message)  # noqa: TRY003
        selected[medication_id] = int(number)
    return selected


def _parse_leaflet_queries(values: list[str]) -> dict[str, str]:
    """Parse ``medication_id=text`` manual AIFA search arguments.

    Parameters
    ----------
    values : list[str]
        Raw command-line manual searches.

    Returns
    -------
    dict[str, str]
        Search text keyed by medication id.

    Raises
    ------
    SaniKeyError
        If a manual search is malformed.
    """

    queries: dict[str, str] = {}
    for value in values:
        medication_id, separator, query = value.partition("=")
        if not medication_id or separator != "=" or not query.strip():
            message = f"ricerca manuale foglio illustrativo non valida: {value}"
            raise SaniKeyError(message)  # noqa: TRY003
        queries[medication_id] = query.strip()
    return queries


def _validate_leaflet_option_ids(
    medication_ids: set[str],
    selected: dict[str, int],
    queries: dict[str, str],
    marked_non_aifa: set[str],
) -> None:
    """Validate medication ids and mutually exclusive leaflet CLI actions.

    Parameters
    ----------
    medication_ids : set[str]
        Curated medication identifiers.
    selected : dict[str, int]
        Explicit candidate choices.
    queries : dict[str, str]
        Explicit manual AIFA searches.
    marked_non_aifa : set[str]
        Medications explicitly excluded from AIFA.

    Returns
    -------
    None

    Raises
    ------
    SaniKeyError
        If an option names an unknown medication or incompatible actions.
    """

    requested = set(selected) | set(queries) | marked_non_aifa
    unknown = sorted(requested - medication_ids)
    if unknown:
        message = f"farmaco non presente nei metadati curati: {unknown[0]}"
        raise SaniKeyError(message)  # noqa: TRY003
    conflicting = sorted(marked_non_aifa & (set(selected) | set(queries)))
    if conflicting:
        message = f"azioni AIFA incompatibili per il farmaco: {conflicting[0]}"
        raise SaniKeyError(message)  # noqa: TRY003


def run_generate_exports(args: argparse.Namespace) -> int:
    """Generate static JSON exports.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for person in _selected_people(config, args.patient):
            metadata = load_curated_metadata(person.metadata_directory)
            result = generate_exports(person, scan_documents(person), metadata)
            print(f"paziente={person.id} dati={_repo_relative_path(result.data_dir)}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_build_web(args: argparse.Namespace) -> int:
    """Generate static frontend files.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for person in _selected_people(config, args.patient):
            result = build_frontend(person)
            print(f"paziente={person.id} web={_repo_relative_path(result.web_dir)}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_export_usb(args: argparse.Namespace) -> int:
    """Export generated artefacts to a USB layout.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        result = export_usb(config, args.target, progress=_progress_from_args(args))
        print(
            f"usb={_repo_relative_path(result.root)} "
            f"pazienti={result.patients} file={result.files}"
        )
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_validate_usb(args: argparse.Namespace) -> int:
    """Validate a generated USB layout.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    if validate_usb(args.target):
        print("stato=ok")
        return 0
    print("stato=invalido")
    return 1


def run_deploy_usb(args: argparse.Namespace) -> int:
    """Build all enabled patients and export them to a USB layout.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        progress = _progress_from_args(args)
        for result in build_all(config, mode="incremental", progress=progress):
            _print_build_result(result)
        export = export_usb(config, args.target, progress=progress)
        print(f"usb={export.root} pazienti={export.patients} file={export.files}")
        if not validate_usb(args.target):
            print("ERRORE: validazione USB non riuscita")
            return 1
    except (SaniKeyError, ValueError) as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def _print_build_result(result: PatientBuildResult) -> None:
    """Print a human-readable patient build result.

    Parameters
    ----------
    result : PatientBuildResult
        Build result.

    Returns
    -------
    None
    """

    print(f"paziente={result.patient_id} stato=ok")
    print(
        f"documenti={result.documents} duplicati={result.duplicates} "
        f"avvisi={result.warnings}"
    )
    print(
        f"documenti_derivati={result.derived_documents} "
        f"istanze_dicom={result.dicom_instances} "
        f"record_totali={result.total_records}"
    )
    print(
        f"documenti_estratti={result.extracted_documents} "
        f"documenti_cached={result.cached_documents}"
    )
    print(f"build_root={_repo_relative_path(result.build_root)}")
    print(f"database={_repo_relative_path(result.database)}")
    print(f"manifest={_repo_relative_path(result.manifest)}")
    print(f"checksums={_repo_relative_path(result.checksums)}")
    print(f"report={_repo_relative_path(result.report)}")
    for warning in result.warning_messages:
        if _should_print_build_warning(warning):
            print(f"AVVISO: {_repo_relative_text(warning)}")
    if result.warnings:
        print("Avvisi=vedi report")


def _should_print_build_warning(warning: str) -> bool:
    """Return whether a build warning should be visible on stdout.

    Parameters
    ----------
    warning : str
        Warning message.

    Returns
    -------
    bool
        ``True`` for warnings that need immediate operator attention.
    """

    return warning.startswith("contenuto documento duplicato saltato.") or (
        "PyMuPDF non ha potuto estrarre il testo PDF" in warning
    )


def _add_config_arguments(
    parser: argparse.ArgumentParser,
    *,
    allow_config_flag: bool = False,
) -> None:
    """Add shared configuration arguments to a subparser.

    Parameters
    ----------
    parser : argparse.ArgumentParser
        Parser to mutate.
    allow_config_flag : bool, optional
        Whether to also expose ``--config`` for commands with other positional
        arguments where a positional config path would be ambiguous.

    Returns
    -------
    None
    """

    if allow_config_flag:
        parser.set_defaults(config=default_accounts_path())
        parser.add_argument(
            "-c",
            "--config",
            dest="config_option",
            type=Path,
            default=None,
            help="Percorso del file config [default: config/accounts.toml]",
        )
    else:
        parser.add_argument(
            "config",
            type=Path,
            nargs="?",
            default=default_accounts_path(),
            help="Percorso del file config [default: config/accounts.toml]",
        )
    parser.add_argument(
        "-r",
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Radice repository usata per i controlli privacy",
    )


def _add_progress_argument(parser: argparse.ArgumentParser) -> None:
    """Add the standard progress-output option.

    Parameters
    ----------
    parser : argparse.ArgumentParser
        Parser to extend.

    Returns
    -------
    None
    """

    parser.add_argument(
        "-q",
        "--no-progress",
        action="store_true",
        help="Disabilita i punti di avanzamento interattivi su stderr",
    )


def _config_path(args: argparse.Namespace) -> Path:
    """Return the effective configuration path from parsed arguments.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    pathlib.Path
        Explicit ``--config`` value, positional value, or default config path.
    """

    config_option = getattr(args, "config_option", None)
    if config_option is not None:
        return cast("Path", config_option)
    config_path = getattr(args, "config", None)
    if config_path is not None:
        return cast("Path", config_path)
    return default_accounts_path()


def _selected_people(
    config: AccountsConfig,
    patient_id: str | None,
) -> tuple[PersonConfig, ...]:
    """Return enabled people, optionally filtered by id.

    Parameters
    ----------
    config : AccountsConfig
        Accounts configuration object.
    patient_id : str | None
        Optional patient id.

    Returns
    -------
    tuple[PersonConfig, ...]
        Selected patient configs.
    """

    people = config.enabled_people()
    if patient_id is None:
        return people
    return tuple(person for person in people if person.id == patient_id)
