"""CLI helpers for sanikey."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import TYPE_CHECKING, Never, cast

from . import __version__
from .build import PatientBuildResult, build_all, build_patient
from .config import default_accounts_path, load_accounts
from .database import build_database
from .dicom import catalog_dicom_studies
from .documents import (
    extract_text,
    scan_documents,
)
from .errors import SaniKeyError
from .exports import generate_exports
from .frontend import build_frontend
from .inspection import inspect_patient_documents
from .integrity import check_source_snapshots, write_source_snapshot
from .metadata import load_curated_metadata
from .observation_imports import import_observations
from .privacy import validate_privacy
from .progress import ProgressDots
from .proposals import generate_manual_proposals, review_proposal
from .usb import export_usb, validate_usb

if TYPE_CHECKING:
    from .config import AccountsConfig, PersonConfig
    from .models import DocumentRecord


class ItalianArgumentParser(argparse.ArgumentParser):
    """Argument parser with Italian diagnostic text.

    Parameters
    ----------
    *args : object
        Positional arguments forwarded to ``argparse.ArgumentParser``.
    **kwargs : object
        Keyword arguments forwarded to ``argparse.ArgumentParser``.
    """

    def error(self, message: str) -> Never:
        """Print a localized parser error and exit.

        Parameters
        ----------
        message : str
            Error message generated by ``argparse``.

        Returns
        -------
        Never

        Raises
        ------
        SystemExit
            Always raised with exit status ``2``.
        """

        self.print_usage()
        self.exit(2, f"{self.prog}: errore: {_translate_argparse_error(message)}\n")


def _translate_argparse_error(message: str) -> str:
    """Translate common ``argparse`` diagnostics to Italian.

    Parameters
    ----------
    message : str
        Diagnostic message generated by ``argparse``.

    Returns
    -------
    str
        Localized diagnostic message.
    """

    replacements = (
        ("unrecognized arguments:", "argomenti non riconosciuti:"),
        ("the following arguments are required:", "argomenti obbligatori mancanti:"),
        ("invalid choice:", "scelta non valida:"),
        ("expected one argument", "atteso un argomento"),
        ("expected at least one argument", "atteso almeno un argomento"),
    )
    translated = message
    for source, target in replacements:
        translated = translated.replace(source, target)
    return translated


def build_parser() -> argparse.ArgumentParser:
    """Build the top-level CLI parser.

    Parameters
    ----------
    None

    Returns
    -------
    argparse.ArgumentParser
        Configured parser for the SaniKey command line.
    """

    parser = ItalianArgumentParser(
        prog="sanikey",
        description="Documenti medici su chiavetta USB",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    subparsers = parser.add_subparsers(
        dest="command",
        parser_class=ItalianArgumentParser,
    )

    info_parser = subparsers.add_parser("info", help="Mostra informazioni progetto")
    info_parser.set_defaults(func=run_info)

    validate_parser = subparsers.add_parser(
        "validate-config",
        help="Valida la configurazione account locale e i vincoli di privacy",
    )
    _add_config_arguments(validate_parser)
    validate_parser.set_defaults(func=run_validate_config)

    list_parser = subparsers.add_parser(
        "list-patients",
        help="Elenca i pazienti configurati",
    )
    _add_config_arguments(list_parser)
    list_parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Include i pazienti disabilitati",
    )
    list_parser.set_defaults(func=run_list_patients)

    scan_parser = subparsers.add_parser(
        "scan-documents",
        help="Scansiona i documenti sorgente configurati",
    )
    _add_config_arguments(scan_parser)
    scan_parser.add_argument("-p", "--patient", help="Scansiona solo un id paziente")
    scan_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Stampa una lista leggibile dei documenti acquisiti",
    )
    scan_parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Scrive la lista dei documenti acquisiti in un file",
    )
    scan_parser.add_argument(
        "-f",
        "--format",
        choices=("text", "csv"),
        default=None,
        help="Formato del file di output, valido solo con --output",
    )
    scan_parser.add_argument(
        "-P",
        "--preflight",
        action="store_true",
        help="Esegue controlli pre-build leggeri su archivi e documenti office",
    )
    scan_parser.add_argument(
        "-S",
        "--no-stage-containers",
        action="store_true",
        help="Salta lo staging dei contenitori durante la scansione",
    )
    _add_progress_argument(scan_parser)
    scan_parser.set_defaults(func=run_scan_documents)

    integrity_parser = subparsers.add_parser(
        "document-integrity",
        help="Crea o verifica snapshot di integrita' dei documenti sorgente",
    )
    _add_config_arguments(integrity_parser, allow_config_flag=True)
    integrity_parser.add_argument(
        "action",
        choices=("before", "after", "check"),
        help="Fase snapshot o azione di verifica",
    )
    integrity_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    integrity_parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        default=Path("local-data"),
        help="Directory per i file snapshot dei pazienti",
    )
    integrity_parser.set_defaults(func=run_document_integrity)

    extract_parser = subparsers.add_parser(
        "extract-text",
        help="Estrae il testo supportato dai documenti sorgente configurati",
    )
    _add_config_arguments(extract_parser)
    extract_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    extract_parser.set_defaults(func=run_extract_text)

    observations_parser = subparsers.add_parser(
        "import-observations",
        help="Importa misurazioni longitudinali da CSV e fogli di calcolo",
    )
    _add_config_arguments(observations_parser, allow_config_flag=True)
    observations_parser.add_argument(
        "patient",
        nargs="?",
        help="Importa solo un id paziente",
    )
    observations_parser.set_defaults(func=run_import_observations)

    dicom_parser = subparsers.add_parser(
        "process-dicom",
        help="Cataloga supporti DICOM e directory di espansione manuale",
    )
    _add_config_arguments(dicom_parser)
    dicom_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    dicom_parser.set_defaults(func=run_process_dicom)

    database_parser = subparsers.add_parser(
        "build-database",
        help="Costruisce database SQLite di archivio per paziente",
    )
    _add_config_arguments(database_parser)
    database_parser.add_argument(
        "-p", "--patient", help="Costruisce solo un id paziente"
    )
    database_parser.set_defaults(func=run_build_database)

    build_patient_parser = subparsers.add_parser(
        "build-patient",
        help="Esegue la pipeline di build locale per un paziente",
    )
    _add_config_arguments(build_patient_parser, allow_config_flag=True)
    build_patient_parser.add_argument("patient")
    build_patient_parser.add_argument(
        "-m",
        "--mode",
        choices=("full", "incremental", "validation"),
        default="incremental",
    )
    _add_progress_argument(build_patient_parser)
    build_patient_parser.set_defaults(func=run_build_patient)

    build_all_parser = subparsers.add_parser(
        "build-all",
        help="Esegue la pipeline di build locale per tutti i pazienti abilitati",
    )
    _add_config_arguments(build_all_parser)
    build_all_parser.add_argument(
        "-m",
        "--mode",
        choices=("full", "incremental", "validation"),
        default="incremental",
    )
    _add_progress_argument(build_all_parser)
    build_all_parser.set_defaults(func=run_build_all)

    update_parser = subparsers.add_parser(
        "update-archive",
        help="Esegue l'aggiornamento incrementale predefinito dell'archivio",
    )
    _add_config_arguments(update_parser)
    update_parser.add_argument("-p", "--patient", help="Aggiorna solo un id paziente")
    update_parser.set_defaults(func=run_update_archive)

    proposals_parser = subparsers.add_parser(
        "generate-proposals",
        help="Genera proposte deterministiche per revisione manuale",
    )
    _add_config_arguments(proposals_parser)
    proposals_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    proposals_parser.set_defaults(func=run_generate_proposals)

    review_parser = subparsers.add_parser(
        "review-proposal",
        help="Approva o respinge una proposta salvata",
    )
    _add_config_arguments(review_parser, allow_config_flag=True)
    review_parser.add_argument("patient")
    review_parser.add_argument("proposal_id")
    review_parser.add_argument("status", choices=("approved", "rejected"))
    review_parser.set_defaults(func=run_review_proposal)

    exports_parser = subparsers.add_parser(
        "generate-exports",
        help="Genera export JSON statici per frontend, ricerca e timeline",
    )
    _add_config_arguments(exports_parser)
    exports_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    exports_parser.set_defaults(func=run_generate_exports)

    web_parser = subparsers.add_parser(
        "build-web",
        help="Genera file frontend statici",
    )
    _add_config_arguments(web_parser)
    web_parser.add_argument("-p", "--patient", help="Elabora solo un id paziente")
    web_parser.set_defaults(func=run_build_web)

    export_parser = subparsers.add_parser(
        "export-usb",
        help="Esporta gli artefatti generati in una directory layout USB",
    )
    _add_config_arguments(export_parser, allow_config_flag=True)
    export_parser.add_argument("target", type=Path)
    _add_progress_argument(export_parser)
    export_parser.set_defaults(func=run_export_usb)

    validate_usb_parser = subparsers.add_parser(
        "validate-usb",
        help="Valida una directory layout USB generata",
    )
    validate_usb_parser.add_argument("target", type=Path)
    validate_usb_parser.set_defaults(func=run_validate_usb)

    deploy_parser = subparsers.add_parser(
        "deploy-usb",
        help="Costruisce tutti i pazienti abilitati e li esporta in un layout USB",
    )
    _add_config_arguments(deploy_parser, allow_config_flag=True)
    deploy_parser.add_argument("target", type=Path)
    _add_progress_argument(deploy_parser)
    deploy_parser.set_defaults(func=run_deploy_usb)
    return parser


def run_info(_args: argparse.Namespace) -> int:
    """Print a minimal project information summary.

    Parameters
    ----------
    _args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    print("progetto=sanikey")
    print("package=sanikey")
    print("cli=sanikey")
    print(f"versione={__version__}")
    return 0


def run_validate_config(args: argparse.Namespace) -> int:
    """Validate accounts configuration and privacy constraints.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        validate_privacy(config, repo_root=args.repo_root)
        for person in config.enabled_people():
            load_curated_metadata(person.metadata_directory)
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    enabled = len(config.enabled_people())
    total = len(config.people)
    print(f"configurazione={config.path}")
    print(f"pazienti={total}")
    print(f"abilitati={enabled}")
    print("stato=ok")
    return 0


def run_list_patients(args: argparse.Namespace) -> int:
    """List configured patient identifiers.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    selected = sorted(
        config.people if args.all else config.enabled_people(),
        key=lambda person: (
            not person.enabled,
            person.id.casefold(),
        ),
    )
    id_width = max((len(person.id) for person in selected), default=0)
    state_width = len("disabilitato") if args.all else len("abilitato")
    for person in selected:
        state = "abilitato" if person.enabled else "disabilitato"
        print(
            f"{person.id:<{id_width}}   {state:<{state_width}}   {person.display_name}"
        )
    return 0


def run_scan_documents(args: argparse.Namespace) -> int:
    """Scan configured source documents and optionally print inventory rows.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    if args.output is None and args.format is not None:
        print("ERRORE: --format e' valido solo con --output")
        return 1
    try:
        config = load_accounts(_config_path(args))
        selected_people = _selected_people(config, args.patient)
        for person in selected_people:
            load_curated_metadata(person.metadata_directory)
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    output_rows: list[tuple[PersonConfig, DocumentRecord]] = []
    progress = _progress_from_args(args)
    for person in selected_people:
        inspection = inspect_patient_documents(
            person,
            preflight=args.preflight,
            stage_containers=not args.no_stage_containers,
            progress=progress,
        )
        warning_messages = (
            *inspection.warning_messages,
            *inspection.preflight_warning_messages,
        )
        summary = (
            f"paziente={person.id} files={len(inspection.inventory)} "
            f"documenti={len(inspection.documents)} "
            f"duplicati={len(inspection.duplicates)} avvisi={len(warning_messages)} "
            f"esclusi={len(inspection.excluded_files)}"
        )
        if inspection.container_staging is not None:
            staged_container_ids = {
                member.container_id for member in inspection.container_staging.members
            }
            summary = (
                f"{summary} archivi_preparati={len(staged_container_ids)} "
                f"membri_in_archivi={len(inspection.container_staging.members)} "
                f"documenti_derivati={len(inspection.container_staging.documents)}"
            )
        print(summary)
        for warning in warning_messages:
            print(f"AVVISO: {warning}")
        if args.verbose:
            print(_format_scan_verbose(person, inspection.documents))
        output_rows.extend((person, document) for document in inspection.documents)
    if args.output is not None:
        try:
            _write_scan_output(
                args.output,
                output_rows,
                output_format=args.format or "text",
            )
        except OSError as exc:
            print(f"ERRORE: impossibile scrivere l'output della scansione: {exc}")
            return 1
    return 0


def run_document_integrity(args: argparse.Namespace) -> int:
    """Create or verify source document integrity snapshots.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected_people = _selected_people(config, args.patient)
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    status = 0
    for person in selected_people:
        try:
            if args.action in {"before", "after"}:
                result = write_source_snapshot(
                    person,
                    label=args.action,
                    output_dir=args.output_dir,
                )
            else:
                result = check_source_snapshots(person, output_dir=args.output_dir)
        except OSError as exc:
            print(f"ERRORE: paziente={person.id} {exc}")
            status = 1
            continue
        print(
            f"paziente={result.patient_id} azione={args.action} "
            f"stato={result.status} sha256={result.sha256_path} "
            f"mtime={result.mtime_path}"
        )
        if result.status != "ok" and args.action == "check":
            status = 1
    return status


def _format_scan_verbose(
    person: PersonConfig,
    documents: tuple[DocumentRecord, ...],
) -> str:
    """Render a readable scan inventory table for stdout.

    Parameters
    ----------
    person : PersonConfig
        Patient configuration.
    documents : tuple[DocumentRecord, ...]
        Deduplicated document records.

    Returns
    -------
    str
        Human-readable table.
    """

    if not documents:
        return f"paziente={person.id} documenti_acquisiti=0"
    rows = [
        (
            "paziente",
            "tipo",
            "data",
            "categoria",
            "sha256",
            "file",
        ),
        *(
            (
                document.patient_id,
                document.kind,
                _format_display_date(document.date),
                document.category,
                document.sha256[:12],
                _source_relative_path(person, document),
            )
            for document in documents
        ),
    ]
    widths = tuple(
        max(len(row[index]) for row in rows) for index in range(len(rows[0]))
    )
    rendered = [f"paziente={person.id} documenti_acquisiti={len(documents)}"]
    for row_index, row in enumerate(rows):
        rendered.append(_format_table_row(row, widths))
        if row_index == 0:
            rendered.append(_format_scan_separator(row, widths))
    return "\n".join(rendered)


def _format_table_row(row: tuple[str, ...], widths: tuple[int, ...]) -> str:
    """Render one table row without padding the final column.

    Parameters
    ----------
    row : tuple[str, ...]
        Table row values.
    widths : tuple[int, ...]
        Column widths.

    Returns
    -------
    str
        Rendered row.
    """

    padded = [value.ljust(widths[index]) for index, value in enumerate(row[:-1])]
    return "  ".join((*padded, row[-1])).rstrip()


def _format_scan_separator(row: tuple[str, ...], widths: tuple[int, ...]) -> str:
    """Render the scan table separator.

    Parameters
    ----------
    row : tuple[str, ...]
        Header row.
    widths : tuple[int, ...]
        Column widths.

    Returns
    -------
    str
        Separator row.
    """

    separator = tuple(
        "-" * (4 if index == len(row) - 1 else min(widths[index], 20))
        for index in range(len(row))
    )
    return _format_table_row(separator, widths)


def _write_scan_output(
    output_path: Path,
    rows: list[tuple[PersonConfig, DocumentRecord]],
    *,
    output_format: str,
) -> None:
    """Write scan inventory rows to a user-selected file.

    Parameters
    ----------
    output_path : pathlib.Path
        Destination file path.
    rows : list[tuple[PersonConfig, DocumentRecord]]
        Patient and document rows.
    output_format : str
        Output format, either ``text`` or ``csv``.

    Returns
    -------
    None
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_format == "csv":
        _write_scan_csv(output_path, rows)
        return
    _write_scan_text(output_path, rows)


def _write_scan_csv(
    output_path: Path,
    rows: list[tuple[PersonConfig, DocumentRecord]],
) -> None:
    """Write scan inventory rows as CSV.

    Parameters
    ----------
    output_path : pathlib.Path
        Destination file path.
    rows : list[tuple[PersonConfig, DocumentRecord]]
        Patient and document rows.

    Returns
    -------
    None
    """

    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            ("paziente", "tipo", "categoria", "data", "titolo", "sha256", "path")
        )
        for _person, document in rows:
            writer.writerow(_scan_legacy_row(document))


def _write_scan_text(
    output_path: Path,
    rows: list[tuple[PersonConfig, DocumentRecord]],
) -> None:
    """Write scan inventory rows in legacy tab-separated text format.

    Parameters
    ----------
    output_path : pathlib.Path
        Destination file path.
    rows : list[tuple[PersonConfig, DocumentRecord]]
        Patient and document rows.

    Returns
    -------
    None
    """

    lines = ["\t".join(_scan_legacy_row(document)) for _person, document in rows]
    output_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def _scan_legacy_row(document: DocumentRecord) -> tuple[str, ...]:
    """Return the legacy scan inventory row.

    Parameters
    ----------
    document : DocumentRecord
        Document record.

    Returns
    -------
    tuple[str, ...]
        Legacy row fields.
    """

    return (
        document.patient_id,
        document.kind,
        document.category,
        document.date or "",
        document.title,
        document.sha256,
        str(document.path),
    )


def _format_display_date(value: str | None) -> str:
    """Format an ISO date for display.

    Parameters
    ----------
    value : str | None
        ISO date or missing value.

    Returns
    -------
    str
        Italian display date or empty string.
    """

    if value is None:
        return ""
    match = value.split("-")
    if len(match) == 3 and all(part.isdigit() for part in match):
        return f"{match[2]}/{match[1]}/{match[0]}"
    return value


def _source_relative_path(person: PersonConfig, document: DocumentRecord) -> str:
    """Return a document path relative to the source root when possible.

    Parameters
    ----------
    person : PersonConfig
        Patient configuration.
    document : DocumentRecord
        Document record.

    Returns
    -------
    str
        Relative path or absolute path fallback.
    """

    try:
        return document.path.relative_to(person.source_documents).as_posix()
    except ValueError:
        return str(document.path)


def run_extract_text(args: argparse.Namespace) -> int:
    """Extract text from configured source documents.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    for person in _selected_people(config, args.patient):
        for document in scan_documents(person):
            extracted = extract_text(document)
            print(
                f"{person.id}\t{document.sha256}\tchars={len(extracted.text)}"
                f"\tavvisi={len(extracted.warnings)}"
            )
            for warning in extracted.warnings:
                print(f"AVVISO: {document.path}: {warning}")
    return 0


def run_process_dicom(args: argparse.Namespace) -> int:
    """Catalog DICOM supports for configured patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    for person in _selected_people(config, args.patient):
        studies = catalog_dicom_studies(person, scan_documents(person))
        print(f"paziente={person.id} studi_dicom={len(studies)}")
        for study in studies:
            extracted = (
                "" if study.extracted_path is None else str(study.extracted_path)
            )
            print(
                "\t".join(
                    (
                        study.patient_id,
                        study.support_kind,
                        str(study.support_path),
                        extracted,
                        str(len(study.viewer_paths)),
                        str(len(study.warnings)),
                        study.study_instance_uid or "",
                        study.study_date or "",
                        study.study_description or "",
                        str(study.instance_count),
                    )
                )
            )
            for warning in study.warnings:
                print(f"AVVISO: {study.support_path}: {warning}")
    return 0


def run_build_database(args: argparse.Namespace) -> int:
    """Build SQLite databases for configured patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    for person in _selected_people(config, args.patient):
        documents = scan_documents(person)
        metadata = load_curated_metadata(person.metadata_directory)
        dicom_studies = catalog_dicom_studies(person, documents)
        result = build_database(person, documents, metadata, dicom_studies)
        print(
            f"paziente={person.id} database={result.path} "
            f"documenti={result.documents} studi_dicom={result.dicom_studies}"
        )
    return 0


def run_build_patient(args: argparse.Namespace) -> int:
    """Run the local build pipeline for one patient.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected = _selected_people(config, args.patient)
        if not selected:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        _print_build_result(
            build_patient(
                selected[0],
                mode=args.mode,
                progress=_progress_from_args(args),
            )
        )
    except (SaniKeyError, ValueError) as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_import_observations(args: argparse.Namespace) -> int:
    """Run observation import for configured patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected = _selected_people(config, args.patient)
        if args.patient and not selected:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        for person in selected:
            result = import_observations(person)
            print(
                f"paziente={result.patient_id} serie={result.series} "
                f"punti={result.points}"
            )
            for warning in result.warnings:
                print(f"AVVISO: {warning}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_build_all(args: argparse.Namespace) -> int:
    """Run the local build pipeline for all enabled patients.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for result in build_all(
            config,
            mode=args.mode,
            progress=_progress_from_args(args),
        ):
            _print_build_result(result)
    except (SaniKeyError, ValueError) as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def _progress_from_args(args: argparse.Namespace) -> ProgressDots:
    """Build a progress reporter from parsed CLI arguments.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    ProgressDots
        Progress reporter configured for the current terminal.
    """

    return ProgressDots(enabled=not getattr(args, "no_progress", False))


def run_update_archive(args: argparse.Namespace) -> int:
    """Run the default incremental archive update.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    if args.patient is None:
        args.mode = "incremental"
        return run_build_all(args)
    args.mode = "incremental"
    args.patient = str(args.patient)
    return run_build_patient(args)


def run_generate_proposals(args: argparse.Namespace) -> int:
    """Generate deterministic manual-review proposals.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for person in _selected_people(config, args.patient):
            proposals = generate_manual_proposals(person.metadata_directory)
            print(f"paziente={person.id} proposte={len(proposals)}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_review_proposal(args: argparse.Namespace) -> int:
    """Approve or reject one stored proposal.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        selected = _selected_people(config, args.patient)
        if not selected:
            print(f"ERRORE: paziente non trovato o disabilitato: {args.patient}")
            return 1
        updated = review_proposal(
            selected[0].metadata_directory,
            args.proposal_id,
            args.status,
        )
        print(f"proposta={updated.id} stato={updated.status}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_generate_exports(args: argparse.Namespace) -> int:
    """Generate static JSON exports.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for person in _selected_people(config, args.patient):
            metadata = load_curated_metadata(person.metadata_directory)
            result = generate_exports(person, scan_documents(person), metadata)
            print(f"paziente={person.id} dati={result.data_dir}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_build_web(args: argparse.Namespace) -> int:
    """Generate static frontend files.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        for person in _selected_people(config, args.patient):
            result = build_frontend(person)
            print(f"paziente={person.id} web={result.web_dir}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_export_usb(args: argparse.Namespace) -> int:
    """Export generated artefacts to a USB layout.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        result = export_usb(config, args.target, progress=_progress_from_args(args))
        print(f"usb={result.root} pazienti={result.patients} file={result.files}")
    except SaniKeyError as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def run_validate_usb(args: argparse.Namespace) -> int:
    """Validate a generated USB layout.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    if validate_usb(args.target):
        print("stato=ok")
        return 0
    print("stato=invalido")
    return 1


def run_deploy_usb(args: argparse.Namespace) -> int:
    """Build all enabled patients and export them to a USB layout.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    int
        Process exit status.
    """

    try:
        config = load_accounts(_config_path(args))
        progress = _progress_from_args(args)
        for result in build_all(config, mode="incremental", progress=progress):
            _print_build_result(result)
        export = export_usb(config, args.target, progress=progress)
        print(f"usb={export.root} pazienti={export.patients} file={export.files}")
        if not validate_usb(args.target):
            print("ERRORE: validazione USB non riuscita")
            return 1
    except (SaniKeyError, ValueError) as exc:
        print(f"ERRORE: {exc}")
        return 1
    return 0


def _print_build_result(result: PatientBuildResult) -> None:
    """Print a human-readable patient build result.

    Parameters
    ----------
    result : PatientBuildResult
        Build result.

    Returns
    -------
    None
    """

    print(f"paziente={result.patient_id} stato=ok")
    print(
        f"documenti={result.documents} duplicati={result.duplicates} "
        f"avvisi={result.warnings}"
    )
    print(
        f"documenti_derivati={result.derived_documents} "
        f"istanze_dicom={result.dicom_instances} "
        f"record_totali={result.total_records}"
    )
    print(
        f"documenti_estratti={result.extracted_documents} "
        f"documenti_cached={result.cached_documents}"
    )
    print(f"build_root={result.build_root}")
    print(f"database={result.database}")
    print(f"manifest={result.manifest}")
    print(f"checksums={result.checksums}")
    print(f"report={result.report}")
    for warning in result.warning_messages:
        if _should_print_build_warning(warning):
            print(f"AVVISO: {warning}")
    if result.warnings:
        print("Avvisi=vedi report")


def _should_print_build_warning(warning: str) -> bool:
    """Return whether a build warning should be visible on stdout.

    Parameters
    ----------
    warning : str
        Warning message.

    Returns
    -------
    bool
        ``True`` for warnings that need immediate operator attention.
    """

    return warning.startswith("contenuto documento duplicato saltato.") or (
        "PyMuPDF non ha potuto estrarre il testo PDF" in warning
    )


def _add_config_arguments(
    parser: argparse.ArgumentParser,
    *,
    allow_config_flag: bool = False,
) -> None:
    """Add shared configuration arguments to a subparser.

    Parameters
    ----------
    parser : argparse.ArgumentParser
        Parser to mutate.
    allow_config_flag : bool, optional
        Whether to also expose ``--config`` for commands with other positional
        arguments where a positional config path would be ambiguous.

    Returns
    -------
    None
    """

    if allow_config_flag:
        parser.set_defaults(config=default_accounts_path())
        parser.add_argument(
            "-c",
            "--config",
            dest="config_option",
            type=Path,
            default=None,
            help="Percorso del file config [default: config/accounts.toml]",
        )
    else:
        parser.add_argument(
            "config",
            type=Path,
            nargs="?",
            default=default_accounts_path(),
            help="Percorso del file config [default: config/accounts.toml]",
        )
    parser.add_argument(
        "-r",
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Radice repository usata per i controlli privacy",
    )


def _add_progress_argument(parser: argparse.ArgumentParser) -> None:
    """Add the standard progress-output option.

    Parameters
    ----------
    parser : argparse.ArgumentParser
        Parser to extend.

    Returns
    -------
    None
    """

    parser.add_argument(
        "-q",
        "--no-progress",
        action="store_true",
        help="Disabilita i punti di avanzamento interattivi su stderr",
    )


def _config_path(args: argparse.Namespace) -> Path:
    """Return the effective configuration path from parsed arguments.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command arguments.

    Returns
    -------
    pathlib.Path
        Explicit ``--config`` value, positional value, or default config path.
    """

    config_option = getattr(args, "config_option", None)
    if config_option is not None:
        return cast("Path", config_option)
    config_path = getattr(args, "config", None)
    if config_path is not None:
        return cast("Path", config_path)
    return default_accounts_path()


def _selected_people(
    config: AccountsConfig,
    patient_id: str | None,
) -> tuple[PersonConfig, ...]:
    """Return enabled people, optionally filtered by id.

    Parameters
    ----------
    config : AccountsConfig
        Accounts configuration object.
    patient_id : str | None
        Optional patient id.

    Returns
    -------
    tuple[PersonConfig, ...]
        Selected patient configs.
    """

    people = config.enabled_people()
    if patient_id is None:
        return people
    return tuple(person for person in people if person.id == patient_id)
